### ISSUE TITLE
Praxis LIVE v3

### ISSUE THREAD

**Issue by neilcsmith-net** [praxis-live/support#34]
Meta issue to track v3 development and minor tasks.

# Roadmap

## alpha 1

- [x] Update infrastructure and compiler to Java 8 #20 
- [x] Update NetBeans platform to v8.1 #23 
- [x] Add PBytes argument type for arbitrary binary data (eg. bytecode)
- [x] Split compiler service out into separate service from code context factory (part of allowing compiler to run in different process / on remote machine)
- [x] OpenGL blit op improvements for identity blending (src & dst same size with no offset) - all blend modes in `video:composite` and `video:xfader` now in OpenGL.
- [x] Graph editor improvements - mouse wheel scrolling, snap alignment, keyboard focus cycling
- [x] FIX `video:gl:p3d` adding alpha to opaque surfaces.
- [x] Deprecate old `core:container:property` component - part of #11 

## alpha 2

- [x] Switch to Darcula look-and-feel - OSX menu bar support.
- [x] Remove legacy GStreamer 0.10 support #35 
- [x] Allow distributed hubs to provide services - compiler, logging, etc. in different process.
- [x] Add http server so resources can be loaded transparently across distributed hubs.
- [x] Add skew to numeric control info - better mapping of slider movement to audio gain, frequency, etc.
- [x] Deprecate old audio components and replace with (stereo) code-based equivalents.
- [x] Add data root type - graphs for asynchronous tasks.

## release candidate

- [x] Fix up GUI appearance, support skew.
- [x] Add proper export of custom components.
- [x] More Java 8 style functional support for audio coding.
- [x] Add Java 8 Stream support to built-in types.
- [x] ~~Add Streamable interface to be used with PBytes - efficient sharing of PVectors, etc. - eg. for geometry.~~ Support Serializable types and Lists of Serializable types using PBytes.
- [x] MIDI / OSC improvements - status (last-message)
- [x] Papercuts #37 (partial)

## Post v3.0
- [ ] Further graph editor improvements - more keyboard control, better zoom control.
- [ ] GUI editor improvements
- [ ] JACK MIDI support #2
- [ ] MIDI / OSC improvements - more mapping components, raw MIDI data, learn function (support skew, automatic binding?)
- [ ] Papercuts #37 (remaining)
