### ISSUE TITLE
Papercuts (v3) - minor usability bugs

### ISSUE THREAD

**Issue by neilcsmith-net** [praxis-live/support#37]
A meta issue to track easily fixable usability bugs, or [papercuts](https://en.wikipedia.org/wiki/Paper_cut_bug). Please add in comments below.
- [x] Add widget alignment in graph editor
- [x] Add scroll wheel support to graph editor
- [x] Improve version display in About and Start Page (build date vs version number)
- [x] Make it clearer that versions on Start Page are notifications of releases, _not the running version_.
- [ ] Write version number into project file and check on build.
- [ ] Check mismatched versions in distributed hubs.
- [x] Add better keyboard control to graph editor

**Comment by maxdee** [comment]
welcome screen displays latest version, not necessarily the version you are running

**Comment by maxdee** [comment]
warn users of version mismatch with projects / distributed hubs

**Comment by maxdee** [comment]
show Prasix LIVE version in About window

**Comment by neilcsmith-net** [comment]
@maxdee Thanks! Added to list in description. Some of the version issues stem from the fact that Praxis LIVE only recently switched to semantic versioning over build date.  The About page does list the build date, but I need to find a way to match the two together in the code.

The start page was always meant to show latest releases and news rather than reflect the version you're currently running, so people can see what features and bug fixes have been added while running an older version.  Somehow the design of that page needs to change to make this more apparent.

**Comment by neilcsmith-net** [comment]
Bumping some of these to version 3.1, particularly around matching versions in files or across hubs.

**Comment by neilcsmith-net** [comment]
Closing this - final two problems to be addressed via #69
