### ISSUE TITLE
Praxis LIVE v3.1

### ISSUE THREAD

**Issue by neilcsmith-net** [praxis-live/support#43]
Meta issue to track v3.1 development and minor tasks.

- [x] Update to latest Processing release
- [ ] Update TinkerForge library
- [ ] Add reset code option that reverts to last saved code, not component default.
